export const tokens = {
  colorBrand: '#2a657e',
  colorBrandDark: '#004b63',
  colorBrandLight: '#bfe8ff',
  colorPrimary: '#2a657e',
  colorPrimaryLight: '#bfe8ff',
  colorPrimaryDark: '#004b63',
  gradientLogin: 'linear-gradient(135deg, #004b63 0%, #006686 100%)',
  colorSecondary: '#7c4dff',
  colorSuccess: '#2e7d32',
  colorWarning: '#f57f17',
  colorError: '#d32f2f',
  colorInfo: '#0288d1',
  colorBg: '#f8f9fa',
  colorSurface: '#ffffff',
  colorSurfaceAlt: '#f1f4f6',
  colorTextPrimary: '#2b3437',
  colorTextSecondary: '#94a3b8',
  colorTextLabel: '#586064',
  colorBorder: '#e3e9ec',
  colorBorderSoft: 'rgba(227, 233, 236, 0.4)',
  colorDivider: '#e3e9ec',
  colorInputBg: '#dbe4e7',
  spacingXs: '4px',
  spacingSm: '8px',
  spacingMd: '16px',
  spacingLg: '24px',
  spacingXl: '32px',
  spacing2xl: '48px',
  radiusSm: '4px',
  radiusMd: '8px',
  radiusLg: '12px',
  radiusXl: '16px',
  radiusFull: '9999px',
  shadowSm: '0 1px 2px rgba(0, 0, 0, 0.05)',
  shadowMd: '0 4px 24px rgba(43, 52, 55, 0.08)',
  shadowLg: '0 20px 40px rgba(25, 28, 30, 0.06)',
  shadowBtn: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
  transitionFast: '150ms ease',
  transitionNormal: '250ms ease',
  transitionSlow: '400ms ease',
  bpMobile: '480px',
  bpTablet: '768px',
  bpDesktop: '1024px',
  bpWide: '1280px',
  headerHeight: '73px',
  sidebarWidth: '260px',
  sidebarCollapsedWidth: '72px',
  contentMaxWidth: '1760px',
  contentPadding: '64px',
} as const;

const cssVariableEntries = [
  ['--color-brand', tokens.colorBrand],
  ['--color-brand-dark', tokens.colorBrandDark],
  ['--color-brand-light', tokens.colorBrandLight],
  ['--color-primary', tokens.colorPrimary],
  ['--color-primary-light', tokens.colorPrimaryLight],
  ['--color-primary-dark', tokens.colorPrimaryDark],
  ['--gradient-login', tokens.gradientLogin],
  ['--color-secondary', tokens.colorSecondary],
  ['--color-success', tokens.colorSuccess],
  ['--color-warning', tokens.colorWarning],
  ['--color-error', tokens.colorError],
  ['--color-info', tokens.colorInfo],
  ['--color-bg', tokens.colorBg],
  ['--color-surface', tokens.colorSurface],
  ['--color-surface-alt', tokens.colorSurfaceAlt],
  ['--color-text-primary', tokens.colorTextPrimary],
  ['--color-text-secondary', tokens.colorTextSecondary],
  ['--color-text-label', tokens.colorTextLabel],
  ['--color-border', tokens.colorBorder],
  ['--color-border-soft', tokens.colorBorderSoft],
  ['--color-divider', tokens.colorDivider],
  ['--color-input-bg', tokens.colorInputBg],
  ['--spacing-xs', tokens.spacingXs],
  ['--spacing-sm', tokens.spacingSm],
  ['--spacing-md', tokens.spacingMd],
  ['--spacing-lg', tokens.spacingLg],
  ['--spacing-xl', tokens.spacingXl],
  ['--spacing-2xl', tokens.spacing2xl],
  ['--radius-sm', tokens.radiusSm],
  ['--radius-md', tokens.radiusMd],
  ['--radius-lg', tokens.radiusLg],
  ['--radius-xl', tokens.radiusXl],
  ['--radius-full', tokens.radiusFull],
  ['--shadow-sm', tokens.shadowSm],
  ['--shadow-md', tokens.shadowMd],
  ['--shadow-lg', tokens.shadowLg],
  ['--shadow-btn', tokens.shadowBtn],
  ['--transition-fast', tokens.transitionFast],
  ['--transition-normal', tokens.transitionNormal],
  ['--transition-slow', tokens.transitionSlow],
  ['--bp-mobile', tokens.bpMobile],
  ['--bp-tablet', tokens.bpTablet],
  ['--bp-desktop', tokens.bpDesktop],
  ['--bp-wide', tokens.bpWide],
  ['--header-height', tokens.headerHeight],
  ['--sidebar-width', tokens.sidebarWidth],
  ['--sidebar-collapsed-width', tokens.sidebarCollapsedWidth],
  ['--content-max-width', tokens.contentMaxWidth],
  ['--content-padding', tokens.contentPadding],
] as const;

export const rootCssVariables = `:root {
${cssVariableEntries.map(([name, value]) => `  ${name}: ${value};`).join('\n')}
}`;
